all: causal_ch0 liveness_ch0 pc_bwd_ch0 pc_fwd_ch0 reg_ch0 unique_ch0 insn_add_ch0 insn_addi_ch0 insn_and_ch0 insn_andi_ch0 insn_auipc_ch0 insn_beq_ch0 insn_bge_ch0 insn_bgeu_ch0 insn_blt_ch0 insn_bltu_ch0 insn_bne_ch0 insn_jal_ch0 insn_jalr_ch0 insn_lb_ch0 insn_lbu_ch0 insn_lh_ch0 insn_lhu_ch0 insn_lui_ch0 insn_lw_ch0 insn_or_ch0 insn_ori_ch0 insn_sb_ch0 insn_sh_ch0 insn_sll_ch0 insn_slli_ch0 insn_slt_ch0 insn_slti_ch0 insn_sltiu_ch0 insn_sltu_ch0 insn_sra_ch0 insn_srai_ch0 insn_srl_ch0 insn_srli_ch0 insn_sub_ch0 insn_sw_ch0 insn_xor_ch0 insn_xori_ch0
causal_ch0: causal_ch0/status
causal_ch0/status:
	sby causal_ch0.sby
.PHONY: causal_ch0
liveness_ch0: liveness_ch0/status
liveness_ch0/status:
	sby liveness_ch0.sby
.PHONY: liveness_ch0
pc_bwd_ch0: pc_bwd_ch0/status
pc_bwd_ch0/status:
	sby pc_bwd_ch0.sby
.PHONY: pc_bwd_ch0
pc_fwd_ch0: pc_fwd_ch0/status
pc_fwd_ch0/status:
	sby pc_fwd_ch0.sby
.PHONY: pc_fwd_ch0
reg_ch0: reg_ch0/status
reg_ch0/status:
	sby reg_ch0.sby
.PHONY: reg_ch0
unique_ch0: unique_ch0/status
unique_ch0/status:
	sby unique_ch0.sby
.PHONY: unique_ch0
insn_add_ch0: insn_add_ch0/status
insn_add_ch0/status:
	sby insn_add_ch0.sby
.PHONY: insn_add_ch0
insn_addi_ch0: insn_addi_ch0/status
insn_addi_ch0/status:
	sby insn_addi_ch0.sby
.PHONY: insn_addi_ch0
insn_and_ch0: insn_and_ch0/status
insn_and_ch0/status:
	sby insn_and_ch0.sby
.PHONY: insn_and_ch0
insn_andi_ch0: insn_andi_ch0/status
insn_andi_ch0/status:
	sby insn_andi_ch0.sby
.PHONY: insn_andi_ch0
insn_auipc_ch0: insn_auipc_ch0/status
insn_auipc_ch0/status:
	sby insn_auipc_ch0.sby
.PHONY: insn_auipc_ch0
insn_beq_ch0: insn_beq_ch0/status
insn_beq_ch0/status:
	sby insn_beq_ch0.sby
.PHONY: insn_beq_ch0
insn_bge_ch0: insn_bge_ch0/status
insn_bge_ch0/status:
	sby insn_bge_ch0.sby
.PHONY: insn_bge_ch0
insn_bgeu_ch0: insn_bgeu_ch0/status
insn_bgeu_ch0/status:
	sby insn_bgeu_ch0.sby
.PHONY: insn_bgeu_ch0
insn_blt_ch0: insn_blt_ch0/status
insn_blt_ch0/status:
	sby insn_blt_ch0.sby
.PHONY: insn_blt_ch0
insn_bltu_ch0: insn_bltu_ch0/status
insn_bltu_ch0/status:
	sby insn_bltu_ch0.sby
.PHONY: insn_bltu_ch0
insn_bne_ch0: insn_bne_ch0/status
insn_bne_ch0/status:
	sby insn_bne_ch0.sby
.PHONY: insn_bne_ch0
insn_jal_ch0: insn_jal_ch0/status
insn_jal_ch0/status:
	sby insn_jal_ch0.sby
.PHONY: insn_jal_ch0
insn_jalr_ch0: insn_jalr_ch0/status
insn_jalr_ch0/status:
	sby insn_jalr_ch0.sby
.PHONY: insn_jalr_ch0
insn_lb_ch0: insn_lb_ch0/status
insn_lb_ch0/status:
	sby insn_lb_ch0.sby
.PHONY: insn_lb_ch0
insn_lbu_ch0: insn_lbu_ch0/status
insn_lbu_ch0/status:
	sby insn_lbu_ch0.sby
.PHONY: insn_lbu_ch0
insn_lh_ch0: insn_lh_ch0/status
insn_lh_ch0/status:
	sby insn_lh_ch0.sby
.PHONY: insn_lh_ch0
insn_lhu_ch0: insn_lhu_ch0/status
insn_lhu_ch0/status:
	sby insn_lhu_ch0.sby
.PHONY: insn_lhu_ch0
insn_lui_ch0: insn_lui_ch0/status
insn_lui_ch0/status:
	sby insn_lui_ch0.sby
.PHONY: insn_lui_ch0
insn_lw_ch0: insn_lw_ch0/status
insn_lw_ch0/status:
	sby insn_lw_ch0.sby
.PHONY: insn_lw_ch0
insn_or_ch0: insn_or_ch0/status
insn_or_ch0/status:
	sby insn_or_ch0.sby
.PHONY: insn_or_ch0
insn_ori_ch0: insn_ori_ch0/status
insn_ori_ch0/status:
	sby insn_ori_ch0.sby
.PHONY: insn_ori_ch0
insn_sb_ch0: insn_sb_ch0/status
insn_sb_ch0/status:
	sby insn_sb_ch0.sby
.PHONY: insn_sb_ch0
insn_sh_ch0: insn_sh_ch0/status
insn_sh_ch0/status:
	sby insn_sh_ch0.sby
.PHONY: insn_sh_ch0
insn_sll_ch0: insn_sll_ch0/status
insn_sll_ch0/status:
	sby insn_sll_ch0.sby
.PHONY: insn_sll_ch0
insn_slli_ch0: insn_slli_ch0/status
insn_slli_ch0/status:
	sby insn_slli_ch0.sby
.PHONY: insn_slli_ch0
insn_slt_ch0: insn_slt_ch0/status
insn_slt_ch0/status:
	sby insn_slt_ch0.sby
.PHONY: insn_slt_ch0
insn_slti_ch0: insn_slti_ch0/status
insn_slti_ch0/status:
	sby insn_slti_ch0.sby
.PHONY: insn_slti_ch0
insn_sltiu_ch0: insn_sltiu_ch0/status
insn_sltiu_ch0/status:
	sby insn_sltiu_ch0.sby
.PHONY: insn_sltiu_ch0
insn_sltu_ch0: insn_sltu_ch0/status
insn_sltu_ch0/status:
	sby insn_sltu_ch0.sby
.PHONY: insn_sltu_ch0
insn_sra_ch0: insn_sra_ch0/status
insn_sra_ch0/status:
	sby insn_sra_ch0.sby
.PHONY: insn_sra_ch0
insn_srai_ch0: insn_srai_ch0/status
insn_srai_ch0/status:
	sby insn_srai_ch0.sby
.PHONY: insn_srai_ch0
insn_srl_ch0: insn_srl_ch0/status
insn_srl_ch0/status:
	sby insn_srl_ch0.sby
.PHONY: insn_srl_ch0
insn_srli_ch0: insn_srli_ch0/status
insn_srli_ch0/status:
	sby insn_srli_ch0.sby
.PHONY: insn_srli_ch0
insn_sub_ch0: insn_sub_ch0/status
insn_sub_ch0/status:
	sby insn_sub_ch0.sby
.PHONY: insn_sub_ch0
insn_sw_ch0: insn_sw_ch0/status
insn_sw_ch0/status:
	sby insn_sw_ch0.sby
.PHONY: insn_sw_ch0
insn_xor_ch0: insn_xor_ch0/status
insn_xor_ch0/status:
	sby insn_xor_ch0.sby
.PHONY: insn_xor_ch0
insn_xori_ch0: insn_xori_ch0/status
insn_xori_ch0/status:
	sby insn_xori_ch0.sby
.PHONY: insn_xori_ch0
